replicaCount: 2
image:
  repository: "<REPLACE_WITH_ACR_LOGIN_SERVER>/devops-demo-app"
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 256Mi }

env:
  APP_ENV: "prod"

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: demo.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

monitoring:
  annotationsScrape: true
  createServiceMonitor: false

podAnnotations: {}
